name: Docker CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Custom tag for image'
        required: true
        default: 'manual-latest'

env:
  IMAGE_NAME: myapp

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set image tag
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV
        else
          echo "TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
        fi

    - name: Build Docker image
      run: docker build -t ${{ secrets.REGISTRY_URL }}/$IMAGE_NAME:$TAG .

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.REGISTRY_URL }}/$IMAGE_NAME:$TAG
        format: 'table'
        output: 'trivy-report.txt'

    - name: Scan image with Trivy
      run: trivy image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
      env:
        REGISTRY: ${{ secrets.REGISTRY_URL }}
        IMAGE_NAME: myapp
        TAG: ${{ github.sha }}


    - name: Push Docker image
      run: docker push ${{ secrets.REGISTRY_URL }}/$IMAGE_NAME:$TAG
